import { Building2, Users, Megaphone, Globe, Target, FileText } from 'lucide-react';
import React from 'react';

export const SERVICES = [
  {
    type: 'core',
    subtitle: "Pillar 01",
    title: "Company Channels",
    description: "We start with an audit to understand where your company page stands, what is working, and what is missing. From there, we identify your audience, define the right platforms to focus on, and shape a clear strategy around how to reach them. We develop communication guidelines, create graphic templates, and build a consistent approach that makes your brand easier to recognise and harder to ignore. Communication is all about showing up in the right places, with the right message, in the right way.",
    whatWeDo: [
      "Channel audit & platform strategy",
      "Audience definition & positioning",
      "Communication guidelines",
      "Graphic templates & visual system",
      "Always-on content production",
      "Community engagement",
      "Consistent brand presence at scale",
    ],
    closingNote: null,
    deliverables: ["Channel Audit", "Platform Strategy", "Communication Guidelines", "Graphic Templates", "Always-on Content", "Community Engagement", "Brand Consistency"],
    icon: React.createElement(Building2, { size: 32 }),
    stats: [],
  },
  {
    type: 'core',
    subtitle: "Pillar 02",
    title: "Leadership Program",
    description: "You tell us which leaders to focus on based on the company's objectives, and we build their personal brands in a direction that supports those goals. We work closely with your leaders to shape a presence that feels credible, relevant, and true to who they are. By building their voice, sharpening their message, and creating the right content around their expertise, we position them as trusted authorities in their field.",
    whatWeDo: [
      "Leader selection aligned to company objectives",
      "Voice, tone and narrative development",
      "Expertise-led content creation",
      "Ghost-writing and editorial support",
      "Thought-leadership positioning",
      "Ongoing coaching and guidance",
    ],
    closingNote: "The result goes beyond individual visibility. It strengthens the company too, showing that your business is home to the voices, ideas, and people helping shape the industry.",
    deliverables: ["Leader Selection", "Voice & Narrative Dev", "Expertise Content", "Ghost-writing", "Thought Leadership", "Ongoing Coaching"],
    icon: React.createElement(Users, { size: 32 }),
    stats: [],
  },
  {
    type: 'core',
    subtitle: "Pillar 03",
    title: "Employee Advocacy",
    description: "Most of your employees are already on LinkedIn, but very few know how to use it in a way that creates real value for the business. At H2H, we build a focused advocacy community made up of employees who are ready to show up, speak up, and represent the brand. We run monthly workshops to train them on how to create high-impact content, and we support them with a steady flow of ideas, guidance, and ready-to-use material.",
    whatWeDo: [
      "Build a focused advocacy community",
      "Monthly workshops and training",
      "High-impact content coaching",
      "Ready-to-use content kits",
      "Ongoing ideas, guidance and support",
      "Personal brand building for employees",
    ],
    closingNote: "The result is a stronger company message carried through a range of authentic voices. Your employees become advocates for the business while building their own personal brands at the same time.",
    deliverables: ["Advocacy Community", "Monthly Workshops", "Content Coaching", "Content Kits", "Ongoing Guidance", "Personal Brand Building"],
    icon: React.createElement(Megaphone, { size: 32 }),
    stats: [],
  },
  {
    type: 'specialized',
    subtitle: "Specialized Service 01",
    title: "Website Design + SEO",
    description: "Your website is often your company's virtual home. We make sure it's the right one. We design and build high-converting, beautiful websites that align with your brand voice and serve as a true hub for your digital presence. And yes, they're built with SEO in mind from day one.",
    whatWeDo: [
      "Strategic Design & Copywriting",
      "Responsive Build (Mobile-first)",
      "SEO Fundamentals",
      "Blog & Content Hub Setup",
    ],
    closingNote: null,
    deliverables: ["Strategic Design & Copywriting", "Responsive Build (Mobile-first)", "SEO Fundamentals", "Blog & Content Hub Setup"],
    icon: React.createElement(Globe, { size: 32 }),
    image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800",
    stats: [
      { label: "Avg. Load Time", value: "<2s" },
      { label: "SEO Score", value: "95+" },
      { label: "Mobile Performance", value: "100%" },
    ],
  },
  {
    type: 'specialized',
    subtitle: "Specialized Service 02",
    title: "Paid Campaigns",
    description: "Great content deserves an audience. We create and manage paid campaigns that amplify your message and drive real business outcomes. From awareness to lead gen, we craft media strategies that meet your goals.",
    whatWeDo: [
      "Paid Strategy & Audience Targeting",
      "Ad Copy & Creative Production",
      "Optimization & A/B Testing",
      "Transparent Reporting",
    ],
    closingNote: null,
    deliverables: ["Paid Strategy & Audience Targeting", "Ad Copy & Creative Production", "Optimization & A/B Testing", "Transparent Reporting"],
    icon: React.createElement(Target, { size: 32 }),
    image: "https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=800",
    stats: [
      { label: "Avg. ROAS", value: "4.2x" },
      { label: "CTR Improvement", value: "+65%" },
      { label: "Cost per Lead", value: "-45%" },
    ],
  },
  {
    type: 'specialized',
    subtitle: "Specialized Service 03",
    title: "Content Writing",
    description: "When it comes to storytelling, words matter! Our team crafts clear, engaging, and on-brand content for every channel. Whether it's for social media, blog posts, email campaigns, or your website — we bring your voice to life in a way that connects.",
    whatWeDo: [
      "Social Captions & Campaigns",
      "Long-form Blog & Thought Leadership",
      "Executive Ghost-writing",
      "Email & Web Copy",
    ],
    closingNote: null,
    deliverables: ["Social Captions & Campaigns", "Long-form Blog & Thought Leadership", "Executive Ghost-writing", "Email & Web Copy"],
    icon: React.createElement(FileText, { size: 32 }),
    image: "https://images.pexels.com/photos/3059745/pexels-photo-3059745.jpeg?auto=compress&cs=tinysrgb&w=800",
    stats: [
      { label: "Content Pieces", value: "50+/mo" },
      { label: "Engagement Rate", value: "+120%" },
      { label: "Brand Voice Score", value: "98%" },
    ],
  },
];

export const PILLARS = SERVICES.filter(s => s.type === 'core');
export const SECONDARY_SERVICES = SERVICES.filter(s => s.type === 'specialized');

export const DIGITAL_HOME = {
  type: 'digital-home' as const,
  subtitle: "Your Digital Home",
  title: "Website / Digital Content Hub",
  description: "Most companies treat their website like a box to tick. We don't. At H2H, we build digital homes — modern, high-impact websites with sharp design, smart movement, and a polished user experience. Then we turn them into content hubs, filled with thought leadership blogs, white papers, infographics, videos, and interviews that bring your brand to life and give people a reason to stay.",
  whatWeDo: [
    "Strategic Design & Copywriting",
    "Responsive Build (Mobile-first)",
    "SEO Fundamentals baked in from day one",
    "Blog & Content Hub Setup",
    "Thought leadership content production",
    "White papers, infographics & video content",
  ],
  closingNote: "Your website is often your company's virtual home. We make sure it's the right one.",
  deliverables: ["Strategic Design", "Responsive Build", "SEO", "Content Hub", "Thought Leadership", "Multi-format Content"],
  icon: React.createElement(Globe, { size: 32 }),
  image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800",
  stats: [],
};
